# Generated by Django 2.2.4 on 2020-02-29 10:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='식당의 이름', max_length=100)),
                ('number', models.CharField(help_text='식당의 전화번호', max_length=20)),
                ('location', models.CharField(help_text='식당의 위치', max_length=50)),
                ('lng', models.FloatField(help_text='식당의 경도')),
                ('lat', models.FloatField(help_text='식당의 위도')),
                ('likes', models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='메뉴의 이름', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, choices=[('b', '아침'), ('l', '점심'), ('d', '저녁'), ('n', '정보 없음')], default='n', help_text='제공 시간', max_length=1)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='quickstart.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 29, 10, 42, 46, 255288))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='quickstart.Restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
