# Generated by Django 3.0.3 on 2020-03-01 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200229_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rname',
            field=models.CharField(default='r', help_text='레스토랑 이름', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 23, 32, 46, 207298)),
        ),
    ]
