# Generated by Django 3.0.3 on 2020-03-03 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200301_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 22, 13, 59, 641368)),
        ),
    ]
