# Generated by Django 3.0.3 on 2020-03-03 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20200303_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 22, 33, 14, 984536)),
        ),
    ]
