# Generated by Django 3.0.3 on 2020-03-13 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20200313_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 19, 59, 9, 406989)),
        ),
    ]
